(loop with vowels = "aeiou"
      as str = (string-downcase (read-line))
      as len = (length str)
      while (> len 1)
      as t1 = (char str (1- len))
      as t2 = (char str (- len 2))
      as t3 = (and (> len 2) (char str (- len 3)))
      when (char= t1 #\e)
      do (setf str (format nil "~aing" (subseq str 0 (1- len)))) 
      (when (char= t2 #\i)
        (setf (char str (- len 2)) #\y))
      else when (and (not (find t1 "xy"))
                     (not (find t3 vowels))
                     (find t2 vowels)
                     (not (find t1 vowels)))
      do (setf str (format nil "~a~aing" str t1)) 
      else
      do (setf str (format nil "~aing" str))
      do (format t "~s~%" str))
